/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wisesynth;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;

import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Brooks
 */
@SuppressWarnings("serial")
public class UserInterface extends javax.swing.JFrame {
	Oscillator os1 = new Oscillator();
	byte [] audioBuffer = new byte[os1.audioBuffer.length]; 
    int waveSelected;
    int volume = 20;
    public boolean isPressed;
    JLabel pressedButton;
    ImageIcon square_button_off = new ImageIcon(getClass().getResource("/images/Button_Square_off.png"));
    ImageIcon triangle_button_off = new ImageIcon(getClass().getResource("/images/Button_Triangle_off.png"));
    ImageIcon sawtooth_button_off = new ImageIcon(getClass().getResource("/images/Button_Sawtooth_off.png"));
    ImageIcon sine_button_off = new ImageIcon(getClass().getResource("/images/Button_Sine_off.png"));
    ImageIcon reverseSawtooth_button_off = new ImageIcon(getClass().getResource("/images/Button_ReverseSawtooth_off.png"));
    ImageIcon white_key = new ImageIcon(getClass().getResource("/images/white_key.png"));
    ImageIcon black_key = new ImageIcon(getClass().getResource("/images/black_key.png"));
    ImageIcon white_key_pressed = new ImageIcon(getClass().getResource("/images/white_key_pressed.png"));
    ImageIcon black_key_pressed = new ImageIcon(getClass().getResource("/images/black_key_pressed.png"));
    ImageIcon qwerty = new ImageIcon(getClass().getResource("/images/QWERTY.png"));

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OwlLogo = new javax.swing.JLabel();
        Button_Sine = new javax.swing.JLabel();
        Button_Square = new javax.swing.JLabel();
        Button_Triangle = new javax.swing.JLabel();
        Button_Sawtooth = new javax.swing.JLabel();
        Button_ReverseSawtooth = new javax.swing.JLabel();
        Slider_Volume = new javax.swing.JSlider();
        BlackKey_Csharp2 = new javax.swing.JLabel();
        BlackKey_Dsharp2 = new javax.swing.JLabel();
        BlackKey_Fsharp2 = new javax.swing.JLabel();
        BlackKey_Gsharp2 = new javax.swing.JLabel();
        BlackKey_Asharp3 = new javax.swing.JLabel();
        WhiteKey_C2 = new javax.swing.JLabel();
        WhiteKey_D2 = new javax.swing.JLabel();
        WhiteKey_E2 = new javax.swing.JLabel();
        WhiteKey_F2 = new javax.swing.JLabel();
        WhiteKey_G2 = new javax.swing.JLabel();
        WhiteKey_A3 = new javax.swing.JLabel();
        WhiteKey_B3 = new javax.swing.JLabel();
        BlackKey_Csharp3 = new javax.swing.JLabel();
        BlackKey_Dsharp3 = new javax.swing.JLabel();
        BlackKey_Fsharp3 = new javax.swing.JLabel();
        BlackKey_Gsharp3 = new javax.swing.JLabel();
        BlackKey_Asharp4 = new javax.swing.JLabel();
        WhiteKey_C3 = new javax.swing.JLabel();
        WhiteKey_D3 = new javax.swing.JLabel();
        WhiteKey_E3 = new javax.swing.JLabel();
        WhiteKey_F3 = new javax.swing.JLabel();
        WhiteKey_G3 = new javax.swing.JLabel();
        WhiteKey_A4 = new javax.swing.JLabel();
        WhiteKey_B4 = new javax.swing.JLabel();
        BlackKey_Csharp4 = new javax.swing.JLabel();
        BlackKey_Dsharp4 = new javax.swing.JLabel();
        BlackKey_Fsharp4 = new javax.swing.JLabel();
        BlackKey_Gsharp4 = new javax.swing.JLabel();
        BlackKey_Asharp5 = new javax.swing.JLabel();
        WhiteKey_C4 = new javax.swing.JLabel();
        WhiteKey_D4 = new javax.swing.JLabel();
        WhiteKey_E4 = new javax.swing.JLabel();
        WhiteKey_F4 = new javax.swing.JLabel();
        WhiteKey_G4 = new javax.swing.JLabel();
        WhiteKey_A5 = new javax.swing.JLabel();
        WhiteKey_B5 = new javax.swing.JLabel();
        tKnob1 = new tknob.TKnob();
        jButton1 = new javax.swing.JButton();
        tKnob2 = new tknob.TKnob();
        tKnob3 = new tknob.TKnob();
        tKnob4 = new tknob.TKnob();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        OwlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        OwlLogo.setText("jLabel1");
        getContentPane().add(OwlLogo);
        OwlLogo.setBounds(810, 30, 80, 109);

        Button_Sine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_Sine_on.png"))); // NOI18N
        Button_Sine.setText("jLabel1");
        Button_Sine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SineMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Sine);
        Button_Sine.setBounds(40, 30, 70, 73);

        Button_Square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_Square_off.png"))); // NOI18N
        Button_Square.setText("jLabel1");
        Button_Square.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SquareMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Square);
        Button_Square.setBounds(120, 30, 70, 73);

        Button_Triangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_Triangle_off.png"))); // NOI18N
        Button_Triangle.setText("jLabel1");
        Button_Triangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TriangleMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Triangle);
        Button_Triangle.setBounds(200, 30, 70, 73);

        Button_Sawtooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_Sawtooth_off.png"))); // NOI18N
        Button_Sawtooth.setText("jLabel1");
        Button_Sawtooth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SawtoothMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Sawtooth);
        Button_Sawtooth.setBounds(280, 30, 70, 73);

        Button_ReverseSawtooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_ReverseSawtooth_off.png"))); // NOI18N
        Button_ReverseSawtooth.setText("jLabel1");
        Button_ReverseSawtooth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ReverseSawtoothMouseClicked(evt);
            }
        });
        getContentPane().add(Button_ReverseSawtooth);
        Button_ReverseSawtooth.setBounds(360, 30, 70, 73);

        Slider_Volume.setOrientation(javax.swing.JSlider.VERTICAL);
        Slider_Volume.setPreferredSize(new java.awt.Dimension(10, 60));
        Slider_Volume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider_VolumeStateChanged(evt);
            }
        });
        getContentPane().add(Slider_Volume);
        Slider_Volume.setBounds(40, 200, 20, 150);

        BlackKey_Csharp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Csharp2.setText("BlackKey_Csharp2");
        BlackKey_Csharp2.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Csharp2);
        BlackKey_Csharp2.setBounds(120, 190, 19, 95);

        BlackKey_Dsharp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Dsharp2.setText("BlackKey_Dsharp2");
        BlackKey_Dsharp2.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Dsharp2);
        BlackKey_Dsharp2.setBounds(160, 190, 19, 95);

        BlackKey_Fsharp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Fsharp2.setText("BlackKey_Fsharp2");
        BlackKey_Fsharp2.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Fsharp2);
        BlackKey_Fsharp2.setBounds(240, 190, 19, 95);

        BlackKey_Gsharp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Gsharp2.setText("BlackKey_Gsharp2");
        BlackKey_Gsharp2.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Gsharp2);
        BlackKey_Gsharp2.setBounds(280, 190, 19, 95);

        BlackKey_Asharp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Asharp3.setText("BlackKey_Asharp3");
        BlackKey_Asharp3.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Asharp3);
        BlackKey_Asharp3.setBounds(320, 190, 19, 95);

        WhiteKey_C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_C2.setText("WhiteKey_C2");
        WhiteKey_C2.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_C2);
        WhiteKey_C2.setBounds(90, 190, 36, 162);

        
        
        WhiteKey_D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_D2.setText("WhiteKey_D2");
        WhiteKey_D2.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_D2);
        WhiteKey_D2.setBounds(130, 190, 36, 162);

        
        
        
        WhiteKey_E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_E2.setText("WhiteKey_E2");
        WhiteKey_E2.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_E2);
        WhiteKey_E2.setBounds(170, 190, 36, 162);

        WhiteKey_F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_F2.setText("WhiteKey_F2");
        WhiteKey_F2.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_F2);
        WhiteKey_F2.setBounds(210, 190, 36, 162);

        WhiteKey_G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_G2.setText("WhiteKey_G2");
        WhiteKey_G2.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_G2);
        WhiteKey_G2.setBounds(250, 190, 36, 162);

        WhiteKey_A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_A3.setText("WhiteKey_A3");
        WhiteKey_A3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_A3);
        WhiteKey_A3.setBounds(290, 190, 36, 162);
        
        
        WhiteKey_B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_B3.setText("WhiteKey_B3");
        WhiteKey_B3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_B3);
        WhiteKey_B3.setBounds(330, 190, 36, 162);

        BlackKey_Csharp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Csharp3.setText("BlackKey_Csharp3");
        BlackKey_Csharp3.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Csharp3);
        BlackKey_Csharp3.setBounds(400, 190, 19, 95);

        
        
        BlackKey_Dsharp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Dsharp3.setText("BlackKey_Dsharp3");
        BlackKey_Dsharp3.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Dsharp3);
        BlackKey_Dsharp3.setBounds(440, 190, 19, 95);

        
        
        BlackKey_Fsharp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Fsharp3.setText("BlackKey_Fsharp3");
        BlackKey_Fsharp3.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Fsharp3);
        BlackKey_Fsharp3.setBounds(520, 190, 19, 95);

        
        
        BlackKey_Gsharp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Gsharp3.setText("BlackKey_Gsharp3");
        BlackKey_Gsharp3.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Gsharp3);
        BlackKey_Gsharp3.setBounds(560, 190, 19, 95);

        
        
        BlackKey_Asharp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Asharp4.setText("BlackKey_Asharp4");
        BlackKey_Asharp4.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Asharp4);
        BlackKey_Asharp4.setBounds(600, 190, 19, 95);

        
        
        WhiteKey_C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_C3.setText("WhiteKey_C3");
        WhiteKey_C3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_C3);
        WhiteKey_C3.setBounds(370, 190, 36, 162);

        
        
        WhiteKey_D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_D3.setText("WhiteKey_D3");
        WhiteKey_D3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_D3);
        WhiteKey_D3.setBounds(410, 190, 36, 162);

        
        
        WhiteKey_E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_E3.setText("WhiteKey_E3");
        WhiteKey_E3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_E3);
        WhiteKey_E3.setBounds(450, 190, 36, 162);

        
        
        WhiteKey_F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_F3.setText("WhiteKey_F3");
        WhiteKey_F3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_F3);
        WhiteKey_F3.setBounds(490, 190, 36, 162);

        
        
        WhiteKey_G3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_G3.setText("WhiteKey_G3");
        WhiteKey_G3.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_G3);
        WhiteKey_G3.setBounds(530, 190, 36, 162);

        
        
        WhiteKey_A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_A4.setText("WhiteKey_A4");
        WhiteKey_A4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_A4);
        WhiteKey_A4.setBounds(570, 190, 36, 162);

        WhiteKey_B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_B4.setText("WhiteKey_B4");
        WhiteKey_B4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_B4);
        WhiteKey_B4.setBounds(610, 190, 36, 162);

        
        
        BlackKey_Csharp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Csharp4.setText("BlackKey_Csharp4");
        BlackKey_Csharp4.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Csharp4);
        BlackKey_Csharp4.setBounds(680, 190, 19, 95);

        
        
        BlackKey_Dsharp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Dsharp4.setText("BlackKey_Dsharp4");
        BlackKey_Dsharp4.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Dsharp4);
        BlackKey_Dsharp4.setBounds(720, 190, 19, 95);

        
        
        BlackKey_Fsharp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Fsharp4.setText("BlackKey_Fsharp4");
        BlackKey_Fsharp4.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Fsharp4);
        BlackKey_Fsharp4.setBounds(800, 190, 19, 95);

        
        
        BlackKey_Gsharp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Gsharp4.setText("BlackKey_Fsharp4");
        BlackKey_Fsharp4.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Gsharp4);
        BlackKey_Gsharp4.setBounds(840, 190, 19, 95);

        
        BlackKey_Asharp5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_key.png"))); // NOI18N
        BlackKey_Asharp5.setText("BlackKey_Asharp5");
        BlackKey_Asharp5.addMouseListener(new MyMouseListener());
        getContentPane().add(BlackKey_Asharp5);
        BlackKey_Asharp5.setBounds(880, 190, 19, 95);

        WhiteKey_C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_C4.setText("WhiteKey_C4");
        WhiteKey_C4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_C4);
        WhiteKey_C4.setBounds(650, 190, 36, 162);

        WhiteKey_D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_D4.setText("WhiteKey_D4");
        WhiteKey_D4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_D4);
        WhiteKey_D4.setBounds(690, 190, 36, 162);

        
        
        WhiteKey_E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_E4.setText("WhiteKey_E4");
        WhiteKey_E4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_E4);
        WhiteKey_E4.setBounds(730, 190, 36, 162);

        WhiteKey_F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_F4.setText("WhiteKey_F4");
        WhiteKey_F4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_F4);
        WhiteKey_F4.setBounds(770, 190, 36, 162);

        WhiteKey_G4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_G4.setText("WhiteKey_G4");
        WhiteKey_G4.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_G4);
        WhiteKey_G4.setBounds(810, 190, 36, 162);

        WhiteKey_A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_A5.setText("WhiteKey_A5");
        WhiteKey_A5.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_A5);
        WhiteKey_A5.setBounds(850, 190, 36, 162);

        WhiteKey_B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white_key.png"))); // NOI18N
        WhiteKey_B5.setText("WhiteKey_B5");
        WhiteKey_B5.addMouseListener(new MyMouseListener());
        getContentPane().add(WhiteKey_B5);
        WhiteKey_B5.setBounds(890, 190, 36, 162);
        getContentPane().add(tKnob1);
        
        
        tKnob1.setBounds(480, 20, 55, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("QWERTY");
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                try {
					jButton1KeyPressed(evt);
				} catch (LineUnavailableException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 120, 80, 23);
        getContentPane().add(tKnob2);
        tKnob2.setBounds(480, 90, 55, 50);
        getContentPane().add(tKnob3);
        tKnob3.setBounds(570, 20, 55, 50);
        getContentPane().add(tKnob4);
        tKnob4.setBounds(570, 90, 55, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/knob_background.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 10, 100, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_metal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_wood2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 170, 1050, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SineMouseClicked
        waveSelected = 0;
        ImageIcon button_on = new ImageIcon(getClass().getResource("/images/Button_Sine_on.png"));
        Button_Sine.setIcon(button_on);
        Button_Square.setIcon(square_button_off);
        Button_Triangle.setIcon(triangle_button_off);
        Button_Sawtooth.setIcon(sawtooth_button_off);
        Button_ReverseSawtooth.setIcon(reverseSawtooth_button_off);
    }//GEN-LAST:event_Button_SineMouseClicked

    private void Button_SquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SquareMouseClicked
        waveSelected = 1;
        ImageIcon button_on = new ImageIcon(getClass().getResource("/images/Button_Square_on.png"));
        Button_Square.setIcon(button_on);
        Button_Sine.setIcon(sine_button_off);
        Button_Triangle.setIcon(triangle_button_off);
        Button_Sawtooth.setIcon(sawtooth_button_off);
        Button_ReverseSawtooth.setIcon(reverseSawtooth_button_off);
    }//GEN-LAST:event_Button_SquareMouseClicked

    private void Button_TriangleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TriangleMouseClicked
        waveSelected = 2;
        ImageIcon button_on = new ImageIcon(getClass().getResource("/images/Button_Triangle_on.png"));
        Button_Triangle.setIcon(button_on);
        Button_Square.setIcon(square_button_off);
        Button_Sine.setIcon(sine_button_off);
        Button_Sawtooth.setIcon(sawtooth_button_off);
        Button_ReverseSawtooth.setIcon(reverseSawtooth_button_off);
    }//GEN-LAST:event_Button_TriangleMouseClicked

    private void Button_SawtoothMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SawtoothMouseClicked
        waveSelected = 3;
        ImageIcon button_on = new ImageIcon(getClass().getResource("/images/Button_Sawtooth_on.png"));
        Button_Sawtooth.setIcon(button_on);
        Button_Square.setIcon(square_button_off);
        Button_Triangle.setIcon(triangle_button_off);
        Button_Sine.setIcon(sine_button_off);
        Button_ReverseSawtooth.setIcon(reverseSawtooth_button_off);
    }//GEN-LAST:event_Button_SawtoothMouseClicked

    private void Button_ReverseSawtoothMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ReverseSawtoothMouseClicked
        waveSelected = 4;
        ImageIcon button_on = new ImageIcon(getClass().getResource("/images/Button_ReverseSawtooth_on.png"));
        Button_ReverseSawtooth.setIcon(button_on);
        Button_Square.setIcon(square_button_off);
        Button_Triangle.setIcon(triangle_button_off);
        Button_Sawtooth.setIcon(sawtooth_button_off);
        Button_Sine.setIcon(sine_button_off);

    }//GEN-LAST:event_Button_ReverseSawtoothMouseClicked

   



    private void Slider_VolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider_VolumeStateChanged
        volume = Slider_Volume.getValue();

    }//GEN-LAST:event_Slider_VolumeStateChanged

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) throws LineUnavailableException {//GEN-FIRST:event_jButton1KeyPressed
        switch (evt.getKeyChar()) {
        
            case 'a': {
                playOscillator(65.41);
                WhiteKey_C2.setIcon(white_key_pressed);
                
                break;
            }
            case 'w': {
                playOscillator(69.30);
                WhiteKey_C2.setIcon(white_key_pressed);
                break;
            }
            case 's': {
                playOscillator(73.4162);
                break;
            }
            case 'e': {
                playOscillator(77.78);
                break;
            }
            case 'd': {
                playOscillator(82.41);
                break;
            }
            case 'f':
            {
            	playOscillator(87.31);
            	break;
            }
            case 't':
            {
            	playOscillator(92.50);
            }
            case 'g':
            {
            	playOscillator(98.00);
            	break;
           	}
            case 'y':
            {
            	playOscillator(103.83);
            	break;
            }
            case 'h':
            {
            	playOscillator(110.00);
            	break;
            }
            case 'u':
            {
            	playOscillator(116.54);
            	break;
            }
            case 'j':
            {
            	playOscillator(123.47);
            	break;
            }
            case 'k':
            {
            	playOscillator(130.81);
            	break;
            } 
            
            //case ';':playOscillator(73.4162); 

        }
        

    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    private void playOscillator(double freq) throws LineUnavailableException {
    	
       
         
        if (waveSelected == 0) {
        	os1.setAmplitube(volume);
        	os1.setFrequency(freq);
            os1.getSampleInterval(freq);
            audioBuffer = os1.generateSineWave(audioBuffer, os1.sampleInterval, os1.amplitude);
            new Thread(){
            	
            	public void run(){
                    os1.flag = true;
            		while(os1.flag){
            			try {
							os1.play(audioBuffer);
						} catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
            		}
            	}
            	
            }.start();

        }
        if (waveSelected == 1) {
        	os1.setAmplitube(volume);
        	os1.setFrequency(freq);
            os1.getSampleInterval(freq);
            audioBuffer = os1.generateSquareWave(os1.audioBuffer, os1.sampleInterval, os1.amplitude);
            os1.flag = true;
            new Thread(){
            	
            	public void run(){
                    os1.flag = true;
            		while(os1.flag){
            			try {
            				os1.play(audioBuffer);
						} catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
            		}
            	}
            	
            }.start();

        }

        if (waveSelected == 2) {
        	os1.setAmplitube(volume);
        	os1.setFrequency(freq);
            os1.getSampleInterval(freq);
            audioBuffer = os1.generateTriangleWave(os1.audioBuffer, os1.sampleInterval, os1.amplitude);
            os1.flag = true;
            new Thread(){
            	
            	public void run(){
                    os1.flag = true;
            		while(os1.flag){
            			try {
							os1.play(audioBuffer);
						} catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
            		}
            	}
            	
            }.start();

        }

        if (waveSelected == 3) {
        	os1.setAmplitube(volume);
        	os1.setFrequency(freq);
            os1.getSampleInterval(freq);
            audioBuffer = os1.generateSawtoothWave(os1.audioBuffer, os1.sampleInterval, os1.amplitude);
            os1.flag = true;
            new Thread(){
            	public void run(){
            		while(os1.flag){
            			try {
							os1.play(audioBuffer);
						} catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
            		}
            	}
            	
            }.start();

        }

        if (waveSelected == 4) {
        	os1.setAmplitube(volume);
        	os1.setFrequency(freq);
            os1.getSampleInterval(freq);
            audioBuffer = os1.generateRevSawtoothWave(os1.audioBuffer, os1.sampleInterval, os1.amplitude);
            os1.flag = true;
            new Thread(){
            	public void run(){
            		while(os1.flag){
            			try {
							os1.play(audioBuffer);
						} catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
            		}
            	}
            	
            }.start();

        }
    }

    public int getVolume() {
        return volume;

    }
    public void setFrequency(String id) throws LineUnavailableException
    {
    	switch(id){
    	
    	case("WhiteKey_C2"):{
    		playOscillator(65.41);
    		//WhiteKey_C2.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Csharp2"):{
    		playOscillator(69.30);
    		//BlackKey_Csharp2.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_D2"):{
    		playOscillator(73.42);
    		//WhiteKey_D2.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Dsharp2"):{
    		playOscillator(77.78);
    		//BlackKey_Dsharp2.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_E2"):{
    		playOscillator(82.41);
    		//WhiteKey_E2.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_F2"):{
    		playOscillator(87.31);
    		//WhiteKey_F2.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Fsharp2"):{
    		playOscillator(92.50);
    		//BlackKey_Fsharp2.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_G2"):{
    		playOscillator(98.00);
    		//WhiteKey_G2.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Gsharp2"):{
    		playOscillator(103.83);
    		//BlackKey_Gsharp2.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_A3"):{
    		playOscillator(110.00);
    		//WhiteKey_A3.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Asharp3"):{
    		playOscillator(116.54);
    		//BlackKey_Asharp3.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_B3"):{
    		playOscillator(123.47);
    		//WhiteKey_B3.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Csharp3"):{
    		playOscillator(138.59);
    		//BlackKey_Csharp3.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Dsharp3"):{
    		playOscillator(155.56);
    		//BlackKey_Dsharp3.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Fsharp3"):{
    		playOscillator(185.00);
    		//BlackKey_Fsharp3.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Gsharp3"):{
    		playOscillator(207.65);
    		//BlackKey_Gsharp3.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Asharp4"):{
    		playOscillator(233.08);
    		//BlackKey_Asharp4.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_C3"):{
    		playOscillator(130.81);
    		//WhiteKey_C3.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_D3"):{
    		playOscillator(146.83);
    		//WhiteKey_D3.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_E3"):{
    		playOscillator(164.81);
    		//WhiteKey_E3.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_F3"):{
    		playOscillator(174.61);
    		//WhiteKey_F3.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_G3"):{
    		playOscillator(196);
    		//WhiteKey_G3.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_A4"):{
    		playOscillator(220);
    		//WhiteKey_A4.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_B4"):{
    		playOscillator(246.94);
    		//WhiteKey_B4.setIcon(white_key_pressed);
    		break;
    	}
    	case("BlackKey_Csharp4"):{
    		playOscillator(277.18);
    		//BlackKey_Csharp4.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Dsharp4"):{
    		playOscillator(311.13);
    		//BlackKey_Dsharp4.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Fsharp4"):{
    		playOscillator(369.99);
    		//BlackKey_Fsharp4.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Gsharp4"):{
    		playOscillator(415.30);
    		//BlackKey_Gsharp4.setIcon(black_key_pressed);
    		break;
    	}
    	case("BlackKey_Asharp5"):{
    		playOscillator(466.16);
    		//BlackKey_Asharp5.setIcon(black_key_pressed);
    		break;
    	}
    	case("WhiteKey_C4"):{
    		playOscillator(261.63);
    		//WhiteKey_C4.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_D4"):{
    		playOscillator(293.66);
    		//WhiteKey_D4.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_E4"):{
    		playOscillator(329.63);
    		//WhiteKey_E4.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_F4"):{
    		playOscillator(349.23);
    		//WhiteKey_F4.setIcon(white_key_pressed);
    		break;
    	}
    	
    	case("WhiteKey_G4"):{
    		playOscillator(392);
    		//WhiteKey_G4.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_A5"):{
    		playOscillator(440);
    		//WhiteKey_A5.setIcon(white_key_pressed);
    		break;
    	}
    	case("WhiteKey_B5"):{
    		playOscillator(493.88);
    		//WhiteKey_B5.setIcon(white_key_pressed);
    		break;
    	}
    	}
    }

		
	

    public class MyMouseListener implements MouseListener{


	@Override
	public void mouseEntered(MouseEvent arg0) {

			
	}

	@Override
	public void mouseExited(MouseEvent arg0) {

	}

	@Override
	public void mousePressed(MouseEvent arg0) {
		System.out.println("pressed");
		JLabel button = (JLabel)arg0.getSource();
		pressedButton = (JLabel)arg0.getSource();
		String id = button.getText();
		isPressed = true;
		if(button.getIcon().equals(white_key))
		{
			button.setIcon(white_key_pressed);
		}
		else if(button.getIcon().equals(black_key))			
		{
			button.setIcon(black_key_pressed);
		}
		try {
			setFrequency(id);
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public void mouseReleased(MouseEvent arg0) {
		System.out.println("released");
		JLabel button = (JLabel)arg0.getSource();
		isPressed = false;
		os1.flag = false; 
		System.out.println(os1.flag);
		if(button.getIcon().equals(white_key_pressed))
			button.setIcon(white_key);
		if(button.getIcon().equals(black_key_pressed))
			button.setIcon(black_key);
		
	}

	@Override
	public void mouseClicked(MouseEvent arg0) {
		
	}
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlackKey_Asharp3;
    private javax.swing.JLabel BlackKey_Asharp4;
    private javax.swing.JLabel BlackKey_Asharp5;
    private javax.swing.JLabel BlackKey_Csharp2;
    private javax.swing.JLabel BlackKey_Csharp3;
    private javax.swing.JLabel BlackKey_Csharp4;
    private javax.swing.JLabel BlackKey_Dsharp2;
    private javax.swing.JLabel BlackKey_Dsharp3;
    private javax.swing.JLabel BlackKey_Dsharp4;
    private javax.swing.JLabel BlackKey_Fsharp2;
    private javax.swing.JLabel BlackKey_Fsharp3;
    private javax.swing.JLabel BlackKey_Fsharp4;
    private javax.swing.JLabel BlackKey_Gsharp2;
    private javax.swing.JLabel BlackKey_Gsharp3;
    private javax.swing.JLabel BlackKey_Gsharp4;
    private javax.swing.JLabel Button_ReverseSawtooth;
    private javax.swing.JLabel Button_Sawtooth;
    private javax.swing.JLabel Button_Sine;
    private javax.swing.JLabel Button_Square;
    private javax.swing.JLabel Button_Triangle;
    private javax.swing.JLabel OwlLogo;
    public javax.swing.JSlider Slider_Volume;
    private javax.swing.JLabel WhiteKey_A3;
    private javax.swing.JLabel WhiteKey_A4;
    private javax.swing.JLabel WhiteKey_A5;
    private javax.swing.JLabel WhiteKey_B3;
    private javax.swing.JLabel WhiteKey_B4;
    private javax.swing.JLabel WhiteKey_B5;
    private javax.swing.JLabel WhiteKey_C2;
    private javax.swing.JLabel WhiteKey_C3;
    private javax.swing.JLabel WhiteKey_C4;
    private javax.swing.JLabel WhiteKey_D2;
    private javax.swing.JLabel WhiteKey_D3;
    private javax.swing.JLabel WhiteKey_D4;
    private javax.swing.JLabel WhiteKey_E2;
    private javax.swing.JLabel WhiteKey_E3;
    private javax.swing.JLabel WhiteKey_E4;
    private javax.swing.JLabel WhiteKey_F2;
    private javax.swing.JLabel WhiteKey_F3;
    private javax.swing.JLabel WhiteKey_F4;
    private javax.swing.JLabel WhiteKey_G2;
    private javax.swing.JLabel WhiteKey_G3;
    private javax.swing.JLabel WhiteKey_G4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private tknob.TKnob tKnob1;
    private tknob.TKnob tKnob2;
    private tknob.TKnob tKnob3;
    private tknob.TKnob tKnob4;
    // End of variables declaration//GEN-END:variables

}